# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: Shamir CLI Unit Tests

on: push

jobs:
  run-integration-tests:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: mnemonic-shamir-secret-sharing-cli

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli libssl-dev libgmock-dev unzip clang-10

    - name: Build GTest Suite
      run: |
        wget https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip
        unzip release-1.11.0.zip
        cd googletest-release-1.11.0
        sudo cmake CMakeLists.txt
        sudo make
        sudo make install

    - name: Build MnemonicsShamirCLI
      run: |
        cd mnemonic-shamir-secret-sharing-cli/MnemonicShamirCLI
        make clean
        make

    - name: Test MnemonicShamirCLI Unit Tests
      run: |
        cd mnemonic-shamir-secret-sharing-cli/UnitTests        
        make clean
        make
        ./build/unit_tests
